# Generated by Django 4.2 on 2024-12-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BusinessUser',
        ),
    ]
